package com.airobot.features.aiserv.event

import com.airobot.features.state.TimerMode

/**
 * Unified sealed class representing AI activity events generated by features.
 */
sealed class AiEvent {
    
    data class AlarmTriggered(
        val id: String,
        val label: String,
        val time: String,
        val triggerTime: Long
    ) : AiEvent()

    data class TimerStarted(
        val id: String,
        val label: String,
        val duration: Int,
        val mode: TimerMode,
        val timestamp: Long
    ) : AiEvent()

    data class TimerReminderTriggered(
        val id: String,
        val label: String,
        val elapsedSeconds: Int,
        val totalSeconds: Int,
        val mode: TimerMode,
        val timestamp: Long
    ) : AiEvent()

    data class TimerFinished(
        val id: String,
        val label: String,
        val duration: Int,
        val targetDuration: Int,
        val mode: TimerMode,
        val timestamp: Long,
        val closeReason: String = "completed", // "completed", "user_interrupted", "emergency_stopped"
        val startTime: Long = 0L,
        val remindersCount: Int = 0
    ) : AiEvent()

    // --- Podcast Events ---
    data class PodcastEpisodeCreated(
        val episodeId: String,
        val title: String,
        val type: String,
        val channelName: String,
        val isDiy: Boolean,
        val timestamp: Long
    ) : AiEvent()

    data class PodcastPlaybackStarted(
        val episodeId: String,
        val title: String,
        val type: String,
        val channelName: String,
        val resumePositionMs: Long,
        val timestamp: Long
    ) : AiEvent()

    data class PodcastPlaybackStopped(
        val episodeId: String,
        val title: String,
        val type: String,
        val channelName: String,
        val progressPercent: Float,
        val listenedMs: Long,
        val timestamp: Long,
        val reason: String = "user_paused"
    ) : AiEvent()

    data class PodcastPlaybackCompleted(
        val episodeId: String,
        val title: String,
        val type: String,
        val channelName: String,
        val durationMs: Long,
        val listenedMs: Long,
        val timestamp: Long
    ) : AiEvent()

    data class PodcastEpisodeFavorited(
        val episodeId: String,
        val title: String,
        val favorite: Boolean,
        val timestamp: Long
    ) : AiEvent()

    data class PodcastSubscriptionChanged(
        val channelId: String,
        val channelTitle: String,
        val isSubscribed: Boolean,
        val timestamp: Long
    ) : AiEvent()
}

