# Project Signing Configuration

# Path to organization-level shared resources (relative to ANDROID_HOME parent)
org_path=keystore

# Specific keystore file within org_path
keystore_relative_path=keystore/release.jks

# Specific properties file within org_path (containing passwords/alias)
props_relative_path=keystore/keystore.properties

# Project Release Metadata?include version code and name
app_name=AiRobot-Assistant
version_name=1.2.0
version_code=10200
